apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: huginn-threaded
  name: huginn-threaded
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: huginn-threaded
