apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-mysql
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: {{ template "fullname" . }}-mysql
    spec:
      containers:
      - name: {{ template "fullname" . }}-mysql
        image: bitnami/mysql:5
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "huginn"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-password
        - name: MYSQL_USER
          value: {{ default "huginn" .Values.databaseUser| quote }}
        ports:
        - containerPort: 3306
